# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: traefik_openid

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/krombel/traefik_openid

# A brief description of what your plugin is doing.
summary: This plugin for Traefik allows it to authenticate requests against an openid provider. It utilizes the OpenID well-known to identify the endpoints to do the login and tries to use JWKs to validate.

# Medias associated to the plugin (optional)
iconPath: foo/icon.png
bannerPath: foo/banner.png

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  ProviderURL: "my-keycloak-url.com/realms/my-realm"
  ClientID: "<CLIENT_ID"
  ClientSecret: "<CLIENT_SECRET"
